Added HTTPS support (bis)
loyd/clickhouse.rs pull request #54
Opened 2022-12-20 20:09 UTC by bezze

I took most of the code from #36 and wrapped it as suggested. Any reviews are welcome.

* Added 'tls' as default feature
* Added 'hyper-tls' as dependency for tls feature
* Now when setting up the client, if compiled with 'tls' feature, the `Client::with_url` method checks for urls that start with 'https:' and creates an `HttpsConnector` for the hyper client

2023-01-03 07:52 UTC, loyd requested changes
Sorry for the late response, there were health problems.

2023-01-03 07:52 UTC, loyd commented on src/lib.rs
> +        if self.url.starts_with("https:") {
From hyper-tls docs:
> By default this connector will use plain HTTP if the URL provided uses the HTTP scheme (eg: http://example.com/).

Thus, it seems possible to just use `HttpsConnector` instead `HttpConnector` inside `impl Default for Client` if the feature is enabled.

2023-01-27 20:02 UTC, gd87429 commented
@bezze @loyd does this mean the driver in its current form supports only `http`?

2023-01-30 05:49 UTC, loyd commented
@gd87429, no, you can specify a custom HTTPS connector, see https://github.com/loyd/clickhouse.rs/pull/27 for details.

2023-02-19 14:50 UTC, merged

2023-02-19 14:50 UTC, loyd commented
I decided to merge it and fix comments on my own.